#pragma once

#include <stdint.h>

/**
 * @ingroup kernel_core
 * @brief User-level event identifiers.
 *
 * @details
 * Defines event codes reserved for user-space
 *
 * @note
 * Event values starting at 50 are reserved for user events
 * to avoid collision with kernel-reserved event identifiers.
 */
enum user_events_e {

	EVT_USERCON_KEY = 50, /**< Console key input event. */	
	EVT_SYS_USER_EVENTS   /**< Upper boundary marker for user events. */
};

/**
 * @ingroup kernel_core
 * @brief Kernel-level event identifiers.
 *
 * @details
 * Defines internal kernel event types generated by
 * the kernel space services.
 *
 * @note
 * These events are typically dispatched by the kernel
 * event manager and must not overlap with user events.
 */
enum kernel_events_e {

	EVT_ONESHOT_TICK,   /**< One-shot timer tick event. */
	EVT_PERIODIC_TICK,  /**< Periodic timer tick event. */
	EVT_KERNEL_DTC,     /**< Kernel data traction code arrival event. */
	EVT_KERNEL_EVENTS   /**< Upper boundary marker for kernel events. */
};

/**
 * @ingroup kernel_core
 * @brief Console key event data.
 *
 * @details
 * Contains input (e.g. keyboard or tty) information associated with
 * a console key event.
 */
struct console_key_s {

    /**
     * @brief ASCII character code.
     *
     * @note
     * May be zero for non-printable keys.
     */
	char code;

	/**
	 * @brief Hardware scan code.
	 *
	 * @details
	 * Raw scan code received from an input controller.
	 * In case of tty it can be zero always
	 */
	uint8_t scan_code;
};

/**
 * @ingroup kernel_core
 * @brief Event payload container.
 *
 * @details
 * Union containing all possible event-specific data types.
 * The active member depends on the associated event identifier.
 *
 * @note
 * The event dispatcher must ensure correct interpretation
 * of the union member based on event type.
 */
union evt_data_u {

	/**
	 * @brief Console key event payload.
	 *
	 * Valid when event type is EVT_USERCON_KEY.
	 */
	struct console_key_s con_key;
};

/**
 * @ingroup kernel_core
 * @brief Event payload alias
 */
typedef union evt_data_u evt_data_t;

/**
 * @ingroup kernel_core
 * @brief Console key event payload alias
 */
typedef struct console_key_s console_key_t;

/**
 * @ingroup kernel_core
 * @brief Event subscriber callback prototype.
 *
 * @param[in] evtData Pointer to event data payload.
 *
 * @details
 * Function type for event subscribers registered with the
 * kernel event dispatcher.
 *
 * The meaning of evtData depends on the event identifier
 * associated with the callback invocation.
 *
 * @pre
 * - evtData can be NULL. In such a case an event has no payload
 * - Subscriber can block unless mandatory not to block by the event consumer design.
 *
 * @note
 * Callback will not execute in interrupt context a kernel makes sure of that
 * Implementation shall be reentrant and time-bounded.
 *
 */
typedef void (*evt_subscriber_t)(evt_data_t const* evtData);
